# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-13 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csamples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctypeattr',
            name='attr_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctypesubattr',
            name='attr_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
