# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-11 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csamples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csampleminimalattr',
            name='attr_name',
            field=models.CharField(max_length=130, unique=True),
        ),
    ]
