# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-12 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csamples', '0002_auto_20181011_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csampledata',
            old_name='csample_sub_attr_value_part1',
            new_name='csample_attr_value_part1',
        ),
        migrations.RenameField(
            model_name='csampledata',
            old_name='csample_sub_attr_value_part2',
            new_name='csample_attr_value_part2',
        ),
    ]
