# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-13 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20171025_2320'),
        ('csamples', '0002_auto_20181013_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctype',
            name='group',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctype',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
