# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-15 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csamples', '0004_auto_20181014_1422'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ctypeattr',
            unique_together=set([('ctype', 'attr_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='ctypesubattr',
            unique_together=set([('parent_attr', 'attr_name')]),
        ),
    ]
