# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-15 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csamples', '0005_auto_20181015_1852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CTypeMinimalAttr',
        ),
    ]
