# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-17 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csamples', '0006_delete_ctypeminimalattr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csamplevirustitration',
            name='csample',
        ),
        migrations.DeleteModel(
            name='CSampleVirusTitration',
        ),
    ]
