# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-17 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csamples', '0007_auto_20181017_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='csampledata',
            name='ctype_attr_value_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='csamplesubdata',
            name='ctype_sub_attr_value_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
