# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:10
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0003_auto_20170328_1436'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biosystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hposition', models.CharField(max_length=10)),
                ('vposition', models.CharField(max_length=10)),
                ('date_in', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('freezing_date', models.DateField(auto_now_add=True)),
                ('registration_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pathology_code', models.CharField(blank=True, max_length=50, null=True)),
                ('freezing_code', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, null=True)),
                ('code39', models.CharField(blank=True, max_length=50, null=True)),
                ('qrcode', models.CharField(blank=True, max_length=50, null=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='containers.BoxContainer')),
            ],
        ),
        migrations.CreateModel(
            name='SampleAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('attachment', models.FileField(blank=True, max_length=250, null=True, upload_to='samples/')),
                ('description', models.TextField(blank=True, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='SampleResearcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='SampleTissue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Sample')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Biosystem')),
            ],
        ),
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tissue', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sampletissue',
            name='tissue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Tissue'),
        ),
    ]
