# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='freezing_date',
            field=models.DateField(),
        ),
    ]
