# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20170329_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='date_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='occupied',
            field=models.BooleanField(default=True),
        ),
    ]
