# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_sample_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='date_in',
            field=models.DateField(),
        ),
    ]
