# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_auto_20170329_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
