# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-16 20:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_auto_20170915_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='oligo_length',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100)]),
        ),
    ]
