# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-16 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_auto_20170916_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledropdown',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
