# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-22 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0011_sampletag_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='tissue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
