# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-22 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0012_sample_tissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='r_e_analysis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
