# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import samples.models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0013_auto_20170923_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleattachment',
            name='attachment',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to=samples.models.upload_path_handler),
        ),
    ]
