# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-14 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0015_auto_20171114_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='freezing_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
