# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-15 20:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0016_auto_20171115_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='freezing_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
