# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-15 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0017_auto_20171115_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='has_glycerol_stock',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
