# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-17 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0019_auto_20171116_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='oligo_sequence',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='target_sequence',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
