# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 12:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='box_horizontal',
        ),
        migrations.RemoveField(
            model_name='container',
            name='box_vertical',
        ),
        migrations.AddField(
            model_name='boxconatiner',
            name='box_horizontal',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='boxconatiner',
            name='box_vertical',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
