# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_assistant_groupresearcher'),
        ('containers', '0002_auto_20170328_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxResearcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='BoxConatiner',
            new_name='BoxContainer',
        ),
        migrations.AddField(
            model_name='boxresearcher',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='containers.BoxContainer'),
        ),
        migrations.AddField(
            model_name='boxresearcher',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupResearcher'),
        ),
    ]
