# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 20:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_auto_20170328_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxcontainer',
            name='box_horizontal',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='boxcontainer',
            name='box_vertical',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
