# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-14 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0005_auto_20170528_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxcontainer',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
