# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 21:20
from __future__ import unicode_literals

import containers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0007_auto_20171023_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='photo',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to=containers.models.upload_path_handler),
        ),
    ]
