# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('pi', models.CharField(max_length=100)),
                ('pi_fullname', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, max_length=150, null=True, upload_to='groups/')),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, validators=[helpers.validators.validate_phone])),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
