# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_assistant_groupresearcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='pi_fullname',
            field=models.CharField(max_length=150),
        ),
    ]
