# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20170508_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to=groups.models.upload_path_handler),
        ),
    ]
