# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_path_handler),
        ),
    ]
